### ISSUE TITLE
Economic_Harm_rule_safety

### ISSUE THREAD

**Issue by MM-WW55** [SaFoLab-WISC/AdaShield#3]
Hello, why are Economic_Harm_rule_safety and Physical_Harm_rule_safety almost identical in the system_prompts.p? I think self harm should not be in the economic harm scenario.

**Comment by rain305f** [comment]
Hi～ thank you for your observation. The issue you pointed out regarding the similarities between Economic_Harm_rule_safety and Physical_Harm_rule_safety in the system_prompts.p has been reviewed and corrected.
